
name: build pdfs
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: build pdfs
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: install tectonic
        run: brew install tectonic
      - name: build pdfs
        run: tectonic */*.tex
