
name: build pdfs
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build pdfs
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          ref: pdfs
      - name: merge
        run: git merge -m 'merge' origin/master
      - name: install tectonic
        run: brew install tectonic
      - name: build pdfs
        run: ./build.bash
